# commands.py
import platform


def full_useful_commands():
    print("Select platform to show commands:")
    print("1. Windows")
    print("2. Linux/Mac")
    print("3. mac")
    choice = input("Enter choice (1/2/3): ").strip()

    windows_cmds = [
        ("systeminfo", "Displays detailed system configuration including OS, hardware, and hotfixes"),
        ("ver", "Shows Windows version"),
        ("wmic os get caption,version,osarchitecture", "Detailed OS information"),
        ("wmic bios get serialnumber", "Displays BIOS serial number"),
        ("wmic csproduct get name,identifyingnumber", "Shows system model and serial number"),
        ("wmic cpu get name,numberofcores,currentclockspeed", "CPU information"),
        ("wmic memorychip get capacity,speed,partnumber", "RAM details"),
        ("wmic diskdrive get model,size,interfacetype", "Physical disk information"),
        ("wmic logicaldisk get name,size,freespace", "Disk space information"),
        ("driverquery", "Lists all installed drivers"),
        ("driverquery /v", "Detailed driver information"),

        ("ipconfig /all", "Complete network adapter configuration"),
        ("getmac /v", "Displays MAC addresses for all network adapters"),
        ("arp -a", "Shows ARP table (IP to MAC mappings)"),
        ("netstat -ano", "Displays all active connections and listening ports with PIDs"),
        ("netstat -r", "Shows routing table"),
        ("netstat -b", "Shows programs creating connections (requires admin)"),
        ("netsh interface show interface", "Lists network interfaces"),
        ("netsh interface ip show config", "Detailed IP configuration"),
        ("netsh wlan show profiles", "Lists stored WiFi profiles"),
        ("netsh wlan show profile name=\"PROFILE\" key=clear", "Shows WiFi password (requires admin)"),
        ("ping -t google.com", "Continuous ping (Ctrl+C to stop)"),
        ("tracert google.com", "Traces route to host showing latency"),
        ("pathping google.com", "Combination of ping and tracert"),
        ("nslookup google.com", "DNS lookup tool"),
        ("net view", "Lists computers in the network domain"),
        ("net config workstation", "Displays workstation service configuration"),

        # User and Session Information
        ("whoami", "Displays current username"),
        ("whoami /priv", "Shows current user privileges"),
        ("whoami /groups", "Lists groups the current user belongs to"),
        ("query user", "Lists logged in users (terminal services)"),
        ("net user", "Lists local user accounts"),
        ("net user username", "Shows information about specific user"),
        ("net localgroup", "Lists local groups"),
        ("net localgroup administrators", "Lists members of administrators group"),
        ("net accounts", "Displays password and login policy"),
        ("net session", "Lists sessions connected to the computer"),
        ("net share", "Lists shared resources"),

        # Process and Service Management
        ("tasklist", "Lists all running processes"),
        ("tasklist /svc", "Lists processes with services"),
        ("tasklist /m", "Lists processes with loaded DLLs"),
        ("taskkill /im process.exe /f", "Force kills a process by name"),
        ("taskkill /pid 1234 /f", "Force kills a process by PID"),
        ("sc query", "Lists all services"),
        ("sc queryex state=all", "Detailed service information"),
        ("sc qc service_name", "Shows service configuration"),
        ("net start", "Lists running services"),
        ("net stop service_name", "Stops a service"),
        ("wmic process get caption,commandline,processid", "Processes with command line arguments"),
        ("wmic service get caption,state,startmode", "Service status and startup type"),
        ("wmic startup get caption,command", "Programs that run at startup"),

        ("dir", "Directory listing"),
        ("dir /s", "Recursive directory listing"),
        ("dir /a", "Shows hidden/system files"),
        ("dir /q", "Shows file ownership"),
        ("tree", "Displays folder tree structure"),
        ("tree /f", "Folder tree with files"),
        ("fsutil fsinfo drives", "Lists all drives"),
        ("fsutil fsinfo drivetype C:", "Shows drive type"),
        ("fsutil fsinfo volumeinfo C:", "Volume information"),
        ("fsutil fsinfo ntfsinfo C:", "NTFS volume information"),
        ("chkdsk", "Checks disk for errors"),
        ("chkdsk /f /r", "Fixes disk errors and recovers bad sectors (requires reboot)"),
        ("defrag C: /a", "Analyzes disk fragmentation"),
        ("defrag C: /x", "Defragments drive"),
        ("vssadmin list shadows", "Lists volume shadow copies"),
        ("vssadmin list volumes", "Lists volumes eligible for shadow copies"),
        ("compact", "Displays or alters file compression"),
        ("cipher /w:C:\\folder", "Wipes free space (secure delete)"),
        ("icacls", "Displays or modifies file ACLs"),
        ("takeown /f file", "Takes ownership of a file"),

        # Event Logs
        ("wevtutil qe system /c:5", "Shows last 5 system events"),
        ("wevtutil qe application /c:5", "Shows last 5 application events"),
        ("wevtutil el", "Lists all event logs"),
        ("eventvwr", "Opens Event Viewer GUI"),

        ("wmic printer list brief", "Lists installed printers"),
        ("wmic sounddev list brief", "Lists sound devices"),
        ("wmic desktopmonitor get screenheight,screenwidth", "Display resolution"),
        ("wmic path win32_videocontroller get name", "Graphics card information"),
        ("wmic path win32_pnpentity get name", "Lists all PnP devices"),
        ("wmic path win32_usbcontrollerdevice get dependent", "Lists USB devices"),
        ("powercfg /energy", "Generates power efficiency report"),
        ("powercfg /batteryreport", "Generates battery health report"),

        ("dism /online /get-features", "Lists Windows features"),
        ("dism /online /get-packages", "Lists installed packages"),
        ("systeminfo | find \"Hotfix(s)\"", "Lists installed hotfixes"),
        ("wmic qfe list", "Lists installed updates"),
        ("reg query HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall",
         "Lists installed programs from registry"),
        ("wmic product get name,version", "Lists installed applications"),

        ("qwinsta", "Lists remote desktop sessions"),
        ("mstsc", "Launches Remote Desktop Connection"),
        ("winrm quickconfig", "Configures WinRM for remote management"),
        ("wmic /node:hostname process list brief", "Remote process listing"),

        ("gpresult /r", "Shows applied group policy settings"),
        ("gpresult /h report.html", "Exports group policy report to HTML"),
        ("secedit /export /cfg sec.txt", "Exports security policy"),
        ("auditpol /get /category:*", "Displays audit policies"),
        ("certmgr.msc", "Opens certificate manager"),
        ("sigverif", "File signature verification tool"),

        ("perfmon", "Opens Performance Monitor"),
        ("perfmon /report", "Generates system diagnostics report"),
        ("typeperf \"\\Processor(_Total)\\% Processor Time\"", "CPU usage in real-time"),
        ("wmic cpu get loadpercentage", "Current CPU load"),
        ("wmic memory get freephysicalmemory", "Available physical memory"),

        ("schtasks", "Lists scheduled tasks"),
        ("wmic startup list full", "Programs that run at startup"),
        ("wmic timezone get caption", "Current timezone"),
        ("wmic nteventlog get path,filename,writeable", "Event log files information"),
        ("wmic recoveros set autoreboot = false", "Disables automatic reboot on crash"),
        ("wmic environment", "Lists environment variables"),
        ("wmic process call create \"cmd.exe\"", "Creates new process"),
        ("wmic /?", "WMI command-line help"),
        ("help", "Lists basic commands"),
        ("help command", "Displays help for specific command"),
        ("clip", "Redirects output to clipboard"),
        ("timeout /t 10", "Waits for 10 seconds"),
        ("shutdown /r /t 0", "Immediate system restart"),
        ("shutdown /s /t 0", "Immediate system shutdown"),
        ("shutdown /l", "Logs off current user"),
        ("control", "Opens Control Panel"),
        ("msinfo32", "System Information GUI"),
        ("dxdiag", "DirectX Diagnostic Tool"),
        ("cleanmgr", "Disk Cleanup utility"),
        ("resmon", "Resource Monitor"),
        ("diskmgmt.msc", "Disk Management console"),
        ("compmgmt.msc", "Computer Management console"),
        ("services.msc", "Services management console"),
        ("devmgmt.msc", "Device Manager"),
        ("eventvwr.msc", "Event Viewer"),
        ("taskschd.msc", "Task Scheduler"),
        ("lusrmgr.msc", "Local Users and Groups"),
        ("firewall.cpl", "Windows Firewall settings"),
        ("appwiz.cpl", "Programs and Features"),
        ("ncpa.cpl", "Network Connections"),
        ("powercfg.cpl", "Power Options"),
        ("sysdm.cpl", "System Properties"),
        ("main.cpl", "Mouse Properties"),
        ("timedate.cpl", "Date and Time"),
        ("mrt", "Windows Malicious Software Removal Tool"),
        ("winver", "Displays Windows version in dialog box")
    ]

    # Linux commands
    linux_cmds = [
        # System Information
        ("uname -a", "Shows kernel and system information"),
        ("hostnamectl", "Shows system hostname and related settings"),
        ("lscpu", "Displays CPU architecture information"),
        ("lshw", "Lists hardware configuration (requires root)"),
        ("lshw -short", "Short hardware listing"),
        ("lsblk", "Lists block devices (disks, partitions)"),
        ("lsusb", "Lists USB devices"),
        ("lspci", "Lists PCI devices"),
        ("lspci -tv", "PCI devices in tree view"),
        ("lsmod", "Lists loaded kernel modules"),
        ("dmidecode", "DMI/SMBIOS hardware info (requires root)"),
        ("hdparm -i /dev/sda", "Shows disk information"),
        ("hdparm -tT /dev/sda", "Performs disk read speed test"),
        ("fdisk -l", "Lists disk partitions (requires root)"),
        ("free -h", "Shows memory usage in human-readable format"),
        ("free -m", "Shows memory usage in MB"),
        ("cat /proc/cpuinfo", "Detailed CPU information"),
        ("cat /proc/meminfo", "Detailed memory information"),
        ("cat /proc/version", "Linux version and gcc version"),
        ("cat /proc/loadavg", "System load averages"),
        ("uptime", "Shows system uptime and load averages"),
        ("vmstat 1 5", "System performance statistics (1s interval, 5 times)"),
        ("iostat", "CPU and I/O statistics"),
        ("sar", "System activity reporter"),
        ("mpstat", "CPU usage statistics"),

        # Network Information
        ("ifconfig -a", "Displays all network interfaces"),
        ("ip addr show", "Modern alternative to ifconfig"),
        ("ip route show", "Shows routing table"),
        ("ip link show", "Shows network interfaces"),
        ("ip -s link", "Network interfaces with statistics"),
        ("ss -tulnp", "Lists listening ports with processes"),
        ("netstat -tulnp", "Alternative to ss (older systems)"),
        ("netstat -s", "Network statistics"),
        ("netstat -r", "Routing table"),
        ("netstat -i", "Network interfaces"),
        ("route -n", "Kernel routing table"),
        ("arp -a", "ARP cache"),
        ("ethtool eth0", "Network interface settings"),
        ("ethtool -S eth0", "Network interface statistics"),
        ("iwconfig", "Wireless interface configuration"),
        ("iwlist scan", "Scans for wireless networks"),
        ("nmcli device show", "NetworkManager device information"),
        ("nmcli connection show", "NetworkManager connections"),
        ("traceroute google.com", "Traces route to host"),
        ("mtr google.com", "Combination of ping and traceroute"),
        ("ping -c 4 google.com", "Sends 4 ICMP echo requests"),
        ("ping6 -c 4 google.com", "IPv6 ping"),
        ("dig google.com", "DNS lookup utility"),
        ("dig google.com +short", "Short DNS lookup"),
        ("dig -x 8.8.8.8", "Reverse DNS lookup"),
        ("nslookup google.com", "Alternative DNS lookup"),
        ("host google.com", "Simple DNS lookup"),
        ("whois google.com", "WHOIS lookup"),
        ("curl ifconfig.me", "Shows public IP address"),
        ("curl -I google.com", "Shows HTTP headers only"),
        ("wget http://example.com/file", "Downloads file from web"),
        ("tcpdump -i eth0", "Captures network traffic"),
        ("tcpdump -i eth0 port 80", "Captures HTTP traffic"),
        ("ufw status", "Uncomplicated Firewall status"),
        ("iptables -L", "Lists firewall rules"),

        # User and Session Information
        ("who", "Shows logged in users"),
        ("w", "Shows logged in users and their processes"),
        ("users", "Lists logged in users"),
        ("last", "Shows last logged in users"),
        ("lastlog", "Shows last login times for all users"),
        ("id", "Shows current user identity"),
        ("groups", "Shows groups for current user"),
        ("getent passwd", "Lists all user accounts"),
        ("getent group", "Lists all groups"),
        ("grep -i shadow /etc/passwd", "Shows system accounts"),
        ("sudo -l", "Lists allowed sudo commands"),
        ("passwd", "Changes user password"),
        ("chage -l username", "Shows password aging information"),
        ("finger username", "User information (if installed)"),

        # Process and Service Management
        ("ps aux", "Lists all running processes"),
        ("ps -ef", "Alternative process listing"),
        ("ps -e --forest", "Process tree"),
        ("ps -u username", "Processes for specific user"),
        ("pstree", "Process tree visualization"),
        ("top", "Interactive process viewer"),
        ("htop", "Enhanced interactive process viewer (if installed)"),
        ("kill -9 PID", "Force kills process by PID"),
        ("killall process_name", "Kills all processes by name"),
        ("pkill process_name", "Kills processes by name"),
        ("pgrep process_name", "Finds PIDs by process name"),
        ("nice -n 10 command", "Runs command with low priority"),
        ("renice 10 -p PID", "Changes priority of running process"),
        ("systemctl list-units --type=service", "Lists all services"),
        ("systemctl status service_name", "Shows service status"),
        ("systemctl start service_name", "Starts a service"),
        ("systemctl stop service_name", "Stops a service"),
        ("systemctl restart service_name", "Restarts a service"),
        ("systemctl enable service_name", "Enables service at boot"),
        ("systemctl disable service_name", "Disables service at boot"),
        ("journalctl -u service_name", "Shows service logs"),
        ("journalctl -b", "Shows boot logs"),
        ("journalctl -f", "Follows system logs in real-time"),
        ("service --status-all", "Lists all services (older systems)"),
        ("chkconfig --list", "Lists services at each runlevel (older systems)"),

        # File System and Storage
        ("df -h", "Shows disk space usage in human-readable format"),
        ("df -i", "Shows inode usage"),
        ("du -sh /path", "Shows directory size summary"),
        ("du -ah /path", "Shows sizes of all files/dirs"),
        ("du -h --max-depth=1 /path", "Shows sizes of first-level dirs"),
        ("ls -la", "Detailed directory listing"),
        ("ls -lh", "File sizes in human-readable format"),
        ("ls -ltr", "Files sorted by modification time (oldest first)"),
        ("tree", "Directory tree (if installed)"),
        ("find / -name filename", "Finds files by name"),
        ("find / -type f -size +100M", "Finds files larger than 100MB"),
        ("find / -mtime -7", "Finds files modified in last 7 days"),
        ("locate filename", "Finds files quickly (requires updatedb)"),
        ("updatedb", "Updates locate database (requires root)"),
        ("mount", "Shows mounted filesystems"),
        ("mount /dev/sda1 /mnt", "Mounts filesystem"),
        ("umount /mnt", "Unmounts filesystem"),
        ("blkid", "Lists block device attributes"),
        ("fsck /dev/sda1", "Filesystem check (unmount first)"),
        ("mkfs.ext4 /dev/sdb1", "Creates ext4 filesystem"),
        ("dd if=/dev/zero of=file.img bs=1M count=100", "Creates 100MB test file"),
        ("dd if=/dev/sda of=disk.img", "Creates disk image (caution!)"),
        ("rsync -avz source/ dest/", "Synchronizes directories"),
        ("tar -czvf archive.tar.gz /path", "Creates compressed tarball"),
        ("tar -xzvf archive.tar.gz", "Extracts compressed tarball"),
        ("gzip file", "Compresses file (creates file.gz)"),
        ("gunzip file.gz", "Decompresses file.gz"),
        ("zcat file.gz", "Views compressed file"),
        ("chmod 755 file", "Changes file permissions"),
        ("chmod +x file", "Makes file executable"),
        ("chown user:group file", "Changes file owner and group"),
        ("chgrp group file", "Changes file group"),
        ("ln -s target linkname", "Creates symbolic link"),
        ("stat file", "Shows detailed file information"),
        ("file filename", "Determines file type"),
        ("md5sum file", "Calculates MD5 checksum"),
        ("sha256sum file", "Calculates SHA-256 checksum"),
        ("cmp file1 file2", "Compares two files byte by byte"),
        ("diff file1 file2", "Shows differences between files"),
        ("tail -f /var/log/syslog", "Follows log file in real-time"),
        ("grep 'error' /var/log/syslog", "Searches for 'error' in log file"),
        ("awk '{print $1}' file", "Prints first column of file"),
        ("sed 's/foo/bar/g' file", "Replaces foo with bar in file"),
        ("sort file", "Sorts lines in file"),
        ("uniq file", "Filters adjacent matching lines"),
        ("wc -l file", "Counts lines in file"),
        ("cut -d: -f1 /etc/passwd", "Extracts first field from passwd file"),
        ("tr 'a-z' 'A-Z' < file", "Translates lowercase to uppercase"),
        ("tee file", "Duplicates output to file and stdout"),
        ("xargs", "Constructs argument lists"),
        ("watch -n 1 command", "Runs command every 1 second"),
        ("crontab -l", "Lists scheduled cron jobs"),
        ("at now + 1 hour", "Schedules one-time job"),
        ("time command", "Measures command execution time"),
        ("timeout 10 command", "Runs command with 10s timeout"),
        ("nohup command &", "Runs command immune to hangups"),
        ("screen", "Terminal multiplexer"),
        ("tmux", "Alternative terminal multiplexer"),
        ("alias ll='ls -la'", "Creates command alias"),
        ("unalias ll", "Removes alias"),
        ("type command", "Shows command type (alias, builtin, etc.)"),
        ("which command", "Shows full path of command"),
        ("whereis command", "Locates binary, source, and manual for command"),
        ("whatis command", "One-line description from man page"),
        ("apropos keyword", "Searches man pages for keyword"),
        ("man -k keyword", "Same as apropos"),
        ("history", "Shows command history"),
        ("history | grep 'apt'", "Searches history for 'apt'"),
        ("!!", "Repeats last command"),
        ("!apt", "Runs last apt command from history"),
        ("shutdown -h now", "Shuts down system immediately"),
        ("reboot", "Reboots system"),
        ("init 6", "Alternative reboot command"),
        ("exit", "Exits current shell session"),
        ("clear", "Clears terminal screen"),
        ("reset", "Resets terminal"),
        ("echo $PATH", "Shows PATH environment variable"),
        ("export PATH=$PATH:/new/path", "Adds to PATH"),
        ("unset VARIABLE", "Removes environment variable"),
        ("env", "Lists all environment variables"),
        ("set", "Shows shell variables and functions"),
        ("source ~/.bashrc", "Reloads bash configuration"),
        ("ssh user@host", "Connects to remote host via SSH"),
        ("scp file user@host:/path", "Copies file to remote host"),
        ("rsync -avz -e ssh src/ user@host:dest/", "Syncs via SSH"),
        ("ssh-keygen", "Generates SSH key pair"),
        ("ssh-copy-id user@host", "Copies SSH key to remote host"),
        ("wget -r --no-parent http://example.com/path/", "Downloads website recursively"),
        ("curl -O http://example.com/file", "Downloads file"),
        ("lynx http://example.com", "Text-based web browser"),
        ("ping -c 4 google.com", "Pings 4 times"),
        ("traceroute google.com", "Traces network path"),
        ("mtr google.com", "Combination of ping and traceroute"),
        ("dig google.com", "DNS lookup"),
        ("host google.com", "Simple DNS lookup"),
        ("whois google.com", "WHOIS lookup"),
        ("ifup eth0", "Brings interface up"),
        ("ifdown eth0", "Takes interface down"),
        ("ethtool eth0", "Network interface settings"),
        ("iptables -L", "Lists firewall rules"),
        ("ufw status", "Shows Uncomplicated Firewall status"),
        ("nc -zv host port", "Tests if port is open"),
        ("telnet host port", "Tests if port is open (older method)"),
        ("openssl s_client -connect host:port", "Tests SSL connection"),
        ("tcpdump -i eth0 -n", "Captures network traffic"),
        ("wireshark", "Graphical packet analyzer (if installed)"),
        ("nmap -sP 192.168.1.0/24", "Discovers hosts on network"),
        ("nmap -sV host", "Scans services on host"),
        ("iptraf", "Interactive network monitor (if installed)"),
        ("iftop", "Displays bandwidth usage (if installed)"),
        ("nethogs", "Shows bandwidth per process (if installed)"),
        ("bmon", "Bandwidth monitor (if installed)"),
        ("vnstat", "Network traffic monitor (if installed)"),
        ("dmesg", "Kernel ring buffer messages"),
        ("dmesg | grep -i error", "Filters kernel errors"),
        ("journalctl -xe", "Shows system logs with details"),
        ("cat /var/log/syslog", "System log (Debian/Ubuntu)"),
        ("cat /var/log/messages", "System log (RHEL/CentOS)"),
        ("tail -f /var/log/syslog", "Follows system log in real-time"),
        ("grep -i error /var/log/syslog", "Searches for errors in log"),
        ("logrotate -f /etc/logrotate.conf", "Rotates log files"),
        ("last -n 10", "Shows last 10 logins"),
        ("last reboot", "Shows reboot history"),
        ("lastlog", "Shows last login for all users"),
        ("who -b", "Shows last system boot time"),
        ("w", "Shows logged in users and their processes"),
        ("finger username", "User information (if installed)"),
        ("id username", "Shows user and group IDs"),
        ("groups username", "Shows user's groups"),
        ("getent passwd username", "Shows user account information"),
        ("getent group groupname", "Shows group information"),
        ("passwd -S username", "Shows password status"),
        ("chage -l username", "Shows password expiration info"),
        ("sudo -l", "Lists allowed sudo commands"),
        ("visudo", "Edits sudoers file safely"),
        ("adduser newuser", "Adds new user"),
        ("deluser olduser", "Deletes user"),
        ("usermod -aG sudo username", "Adds user to sudo group"),
        ("groupadd newgroup", "Adds new group"),
        ("groupdel oldgroup", "Deletes group"),
        ("usermod -g groupname username", "Changes user's primary group"),
        ("gpasswd -a username groupname", "Adds user to secondary group"),
        ("gpasswd -d username groupname", "Removes user from group"),
        ("pwck", "Verifies integrity of password files"),
        ("grpck", "Verifies integrity of group files"),
        ("vipw", "Edits password file safely"),
        ("vigr", "Edits group file safely"),
        ("chsh -s /bin/bash username", "Changes user's shell"),
        ("chfn username", "Changes user's finger information"),
        ("newgrp groupname", "Changes primary group temporarily"),
        ("su - username", "Switches user with environment"),
        ("sudo -u username command", "Runs command as another user"),
        ("sudo -i", "Starts interactive root shell"),
        ("sudo !!", "Runs previous command with sudo"),
        ("wall \"message\"", "Sends message to all users"),
        ("write username", "Sends message to specific user"),
        ("mesg y", "Enables receiving messages"),
        ("mesg n", "Disables receiving messages"),
        ("talk username", "Starts interactive chat"),
        ("finger username", "Shows user information"),
        ("lastcomm command", "Shows command execution history"),
        ("ac -p", "Shows user login time statistics"),
        ("sa", "Summarizes accounting information"),
        ("sar -u", "CPU utilization report"),
        ("sar -r", "Memory utilization report"),
        ("sar -b", "I/O statistics report"),
        ("sar -n DEV", "Network statistics report"),
        ("iostat", "CPU and I/O statistics"),
        ("mpstat", "CPU statistics"),
        ("vmstat", "Virtual memory statistics"),
        ("free", "Memory usage"),
        ("top", "Interactive process viewer"),
        ("htop", "Enhanced process viewer"),
        ("glances", "System monitoring tool"),
        ("nmon", "System performance monitoring"),
        ("dstat", "Versatile resource statistics"),
        ("iftop", "Network bandwidth usage"),
        ("iotop", "Disk I/O usage by process"),
        ("lsof", "Lists open files and processes"),
        ("lsof -i :80", "Shows processes using port 80"),
        ("lsof -u username", "Shows files opened by user"),
        ("fuser -v /path", "Shows processes using file/directory"),
        ("strace -p PID", "Traces system calls of process"),
        ("ltrace -p PID", "Traces library calls of process"),
        ("gdb -p PID", "Debugger for running process"),
        ("kill -3 PID", "Sends SIGQUIT to process (thread dump)"),
        ("killall -9 processname", "Kills all processes by name"),
        ("pkill -f pattern", "Kills processes matching pattern"),
        ("pgrep -fl pattern", "Finds PIDs matching pattern"),
        ("timeout 10 command", "Runs command with timeout"),
        ("watch -n 1 command", "Runs command every second"),
        ("crontab -l", "Lists cron jobs"),
        ("crontab -e", "Edits cron jobs"),
        ("at now + 1 hour", "Schedules one-time job"),
        ("batch", "Schedules job when system load permits"),
        ("anacron", "Runs periodic jobs (for laptops)"),
        ("systemctl list-timers", "Lists systemd timers"),
        ("logrotate -f /etc/logrotate.conf", "Rotates log files"),
        ("logwatch", "Analyzes and reports on logs"),
        ("swapon -s", "Shows swap usage"),
        ("swapon /dev/sdb2", "Activates swap partition"),
        ("swapoff /dev/sdb2", "Deactivates swap partition"),
        ("mkswap /dev/sdb2", "Formats partition as swap"),
        ("free -h", "Shows memory and swap usage"),
        ("vmstat 1 5", "Virtual memory statistics"),
        ("slabtop", "Kernel slab cache information"),
        ("pmap PID", "Process memory map"),
        ("ps_mem.py", "Shows memory usage per process"),
        ("valgrind --leak-check=yes program", "Memory leak detector"),
        ("strace -e trace=file command", "Traces file operations"),
        ("ltrace command", "Traces library calls"),
        ("ldd /path/to/binary", "Lists shared library dependencies"),
        ("ldconfig -p", "Lists cached shared libraries"),
        ("objdump -d /path/to/binary", "Disassembles binary"),
        ("nm /path/to/binary", "Lists symbols from binary"),
        ("strings /path/to/binary", "Extracts strings from binary"),
        ("readelf -a /path/to/binary", "Displays ELF information"),
        ("file /path/to/binary", "Identifies file type"),
        ("hexdump -C /path/to/file", "Hex dump of file"),
        ("xxd /path/to/file", "Hex dump with ASCII"),
        ("md5sum /path/to/file", "Calculates MD5 checksum"),
        ("sha1sum /path/to/file", "Calculates SHA-1 checksum"),
        ("sha256sum /path/to/file", "Calculates SHA-256 checksum"),
        ("sha512sum /path/to/file", "Calculates SHA-512 checksum"),
        ("gpg --gen-key", "Generates GPG key pair"),
        ("gpg --encrypt file", "Encrypts file"),
        ("gpg --decrypt file.gpg", "Decrypts file"),
        ("gpg --sign file", "Creates digital signature"),
        ("gpg --verify signature", "Verifies signature"),
        ("openssl genrsa -out key.pem 2048", "Generates RSA private key"),
        ("openssl req -new -x509 -key key.pem -out cert.pem -days 365", "Creates self-signed certificate"),
        ("openssl s_client -connect host:port", "Tests SSL connection"),
        ("ssh-keygen -t rsa -b 4096", "Generates SSH key pair"),
        ("ssh-copy-id user@host", "Copies SSH key to remote host"),
        ("ssh -i key.pem user@host", "Connects with specific key"),
        ("scp -i key.pem file user@host:/path", "Copies file with specific key"),
        ("rsync -avz -e \"ssh -i key.pem\" src/ user@host:dest/", "Syncs with specific key"),
        ("tar -czvf - dir/ | ssh user@host \"tar -xzvf -\"", "Streaming tar over SSH"),
        ("dd if=/dev/sda | ssh user@host \"dd of=/path/to/image\"", "Streaming disk image over SSH"),
        ("nc -l 1234 > file", "Receives file over netcat"),
        ("nc host 1234 < file", "Sends file over netcat"),
        ("socat", "Multipurpose relay"),
        ("screen", "Terminal multiplexer"),
        ("tmux", "Alternative terminal multiplexer"),
        ("byobu", "Enhanced terminal multiplexer"),
        ("script", "Records terminal session"),
        ("scriptreplay", "Plays back recorded session"),
        ("expect", "Automates interactive programs"),
        ("dialog", "Creates interactive dialogs"),
        ("whiptail", "Alternative to dialog"),
        ("zenity", "Creates GTK+ dialogs"),
        ("kdialog", "Creates KDE dialogs"),
        ("notify-send \"Message\"", "Sends desktop notification"),
        ("xmessage \"Message\"", "Shows X11 message box"),
        ("xterm", "Launches X terminal"),
        ("xeyes", "Fun X11 application"),
        ("xclock", "X11 clock"),
        ("xcalc", "X11 calculator"),
        ("xlogo", "X11 logo"),
        ("xwininfo", "Window information"),
        ("xprop", "Window properties"),
        ("xrandr", "Display settings"),
        ("xinput", "Input device settings"),
        ("xmodmap", "Keyboard modifier mapping"),
        ("setxkbmap", "Keyboard layout settings"),
        ("xset", "X11 preferences"),
        ("xauth", "X11 authentication"),
        ("xhost", "X11 access control"),
        ("xdpyinfo", "X11 display information"),
        ("glxinfo", "OpenGL information"),
        ("glxgears", "OpenGL test"),
        ("vncserver", "Starts VNC server"),
        ("x11vnc", "Shares current X session"),
        ("Xvfb :1 -screen 0 1024x768x16", "Creates virtual framebuffer"),
        ("startx", "Starts X session"),
        ("xinit", "Alternative to startx"),
        ("twm", "Minimal window manager"),
        ("xmonad", "Tiling window manager"),
        ("i3", "Another tiling window manager"),
        ("awesome", "Dynamic window manager"),
        ("fluxbox", "Lightweight window manager"),
        ("openbox", "Another lightweight WM"),
        ("blackbox", "Minimal window manager"),
        ("fvwm", "Highly configurable WM"),
        ("enlightenment", "Feature-rich WM"),
        ("gnome-session", "Starts GNOME"),
        ("startkde", "Starts KDE"),
        ("xfce4-session", "Starts XFCE"),
        ("lxde-session", "Starts LXDE"),
        ("mate-session", "Starts MATE"),
        ("cinnamon-session", "Starts Cinnamon"),
        ("unity", "Starts Unity"),
        ("lightdm", "Display manager"),
        ("gdm", "GNOME display manager"),
        ("kdm", "KDE display manager"),
        ("sddm", "Modern display manager"),
        ("xdm", "Original X display manager"),
        ("vncviewer host:1", "Connects to VNC server"),
        ("rdesktop host", "Connects to RDP server"),
        ("remmina", "Remote desktop client"),
        ("vinagre", "Another remote desktop client"),
        ("krfb", "KDE remote desktop"),
        ("gnome-remote-desktop", "GNOME remote desktop"),
        ("x2go", "Remote desktop with session management"),
        ("nxclient", "NoMachine client"),
        ("teamviewer", "Commercial remote desktop"),
        ("anydesk", "Alternative remote desktop"),
        ("sshfs user@host:/path /mnt", "Mounts remote directory via SSH"),
        ("curlftpfs host:/path /mnt", "Mounts FTP as filesystem"),
        ("mount -t cifs //host/share /mnt", "Mounts Windows share"),
        ("mount -t nfs host:/path /mnt", "Mounts NFS share"),
        ("smbclient -L host", "Lists SMB shares"),
        ("nmblookup -A host", "NetBIOS name lookup"),
        ("wbinfo -u", "Lists Windows domain users"),
        ("getent passwd", "Lists all users (including domain)"),
        ("realm list", "Shows domain membership"),
        ("realm join domain", "Joins Active Directory domain"),
        ("kinit username", "Kerberos authentication"),
        ("klist", "Shows Kerberos tickets"),
        ("ipa", "FreeIPA client"),
        ("sssd", "System Security Services Daemon"),
        ("pam-auth-update", "Updates PAM configuration"),
        ("authconfig", "Configures authentication (RHEL)"),
        ("chage -l username", "Shows password aging info"),
        ("passwd -S username", "Shows password status"),
        ("pwck", "Password file integrity check"),
        ("grpck", "Group file integrity check"),
        ("vipw", "Edits password file safely"),
        ("vigr", "Edits group file safely"),
        ("newusers file", "Batch creates users"),
        ("chpasswd", "Batch changes passwords"),
        ("pam_tally2 --user=username", "Shows failed login attempts"),
        ("faillock --user username", "Shows failed attempts (modern)"),
        ("lastb", "Shows bad login attempts"),
        ("ausearch -m USER_LOGIN", "Audit log for logins"),
        ("aureport -l", "Login report from audit logs"),
        ("auditctl -l", "Lists audit rules"),
        ("auditctl -w /path -p war -k keyname", "Watches file for changes"),
        ("aureport -f", "File access report"),
        ("ausearch -f /path", "Searches audit log for file access"),
        ("setfacl -m u:username:rwx file", "Adds ACL for user"),
        ("getfacl file", "Shows ACLs"),
        ("chattr +i file", "Makes file immutable"),
        ("lsattr file", "Shows file attributes"),
        ("tune2fs -l /dev/sda1", "Shows ext filesystem info"),
        ("debugfs /dev/sda1", "Ext filesystem debugger"),
        ("fsck.ext4 /dev/sda1", "Checks ext4 filesystem"),
        ("mkfs.ext4 /dev/sdb1", "Creates ext4 filesystem"),
        ("resize2fs /dev/sdb1", "Resizes ext filesystem"),
        ("e2fsck /dev/sda1", "Alternative fsck for ext"),
        ("dumpe2fs /dev/sda1", "Dumps ext filesystem info"),
        ("xfs_info /mountpoint", "Shows XFS info"),
        ("xfs_repair /dev/sda1", "Repairs XFS filesystem"),
        ("xfs_growfs /mountpoint", "Grows XFS filesystem"),
        ("mkfs.xfs /dev/sdb1", "Creates XFS filesystem"),
        ("btrfs filesystem show", "Shows BTRFS filesystems"),
        ("btrfs subvolume list /", "Lists BTRFS subvolumes"),
        ("btrfs filesystem df /", "BTRFS space usage"),
        ("btrfs balance start /", "Balances BTRFS filesystem"),
        ("btrfs scrub start /", "Starts BTRFS scrub"),
        ("btrfs device add /dev/sdb1 /", "Adds device to BTRFS"),
        ("mkfs.btrfs /dev/sdb1", "Creates BTRFS filesystem"),
        ("zpool list", "Lists ZFS pools"),
        ("zfs list", "Lists ZFS filesystems"),
        ("zpool status", "Shows ZFS pool status"),
        ("zfs get all pool/filesystem", "Shows ZFS properties"),
        ("zpool scrub pool", "Starts ZFS scrub"),
        ("zpool add pool device", "Adds device to ZFS pool"),
        ("mdadm --detail /dev/md0", "Shows RAID array details"),
        ("mdadm --create /dev/md0 --level=1 --raid-devices=2 /dev/sda1 /dev/sdb1", "Creates RAID array"),
        ("mdadm --manage /dev/md0 --add /dev/sdc1", "Adds device to RAID"),
        ("lvmdiskscan", "Scans for LVM physical volumes"),
        ("pvdisplay", "Shows physical volumes"),
        ("vgdisplay", "Shows volume groups"),
        ("lvdisplay", "Shows logical volumes"),
        ("pvcreate /dev/sdb1", "Creates physical volume"),
        ("vgcreate vgname /dev/sdb1", "Creates volume group"),
        ("lvcreate -L 10G -n lvname vgname", "Creates logical volume"),
        ("lvextend -L +5G /dev/vgname/lvname", "Extends logical volume"),
        ("resize2fs /dev/vgname/lvname", "Resizes filesystem after LV extension"),
        ("lvremove /dev/vgname/lvname", "Removes logical volume"),
        ("vgremove vgname", "Removes volume group"),
        ("pvremove /dev/sdb1", "Removes physical volume"),
        ("multipath -ll", "Shows multipath devices"),
        ("iscsiadm -m discovery -t st -p host", "Discovers iSCSI targets"),
        ("iscsiadm -m node -T targetname -p host -l", "Logs in to iSCSI target"),
        ("drbdadm status", "Shows DRBD status"),
        ("gluster peer status", "Shows GlusterFS peers"),
        ("gluster volume info", "Shows GlusterFS volumes"),
        ("ceph -s", "Shows Ceph status"),
        ("ceph osd tree", "Shows Ceph OSD hierarchy"),
        ("rados df", "Shows Ceph RADOS usage"),
        ("rbd list", "Lists RBD images"),
        ("swift list", "Lists OpenStack Swift containers"),
        ("openstack server list", "Lists OpenStack instances"),
        ("nova list", "Alternative OpenStack instance list"),
        ("virsh list --all", "Lists all libvirt domains"),
        ("virsh dominfo domain", "Shows domain information"),
        ("virsh dumpxml domain", "Shows domain XML configuration"),
        ("virsh edit domain", "Edits domain configuration"),
        ("virsh start domain", "Starts domain"),
        ("virsh shutdown domain", "Shuts down domain gracefully"),
        ("virsh destroy domain", "Force stops domain"),
        ("virsh console domain", "Connects to domain console"),
        ("virsh attach-disk domain /path/to/disk vdb --driver qemu --subdriver raw --type disk",
         "Attaches disk to domain"),
        ("virsh detach-disk domain vdb", "Detaches disk from domain"),
        ("virsh snapshot-create domain", "Creates snapshot"),
        ("virsh snapshot-list domain", "Lists snapshots"),
        ("virsh snapshot-revert domain snapshot", "Reverts to snapshot"),
        ("virsh autostart domain", "Enables autostart for domain"),
        ("virsh net-list --all", "Lists virtual networks"),
        ("virsh net-info network", "Shows network information"),
        ("virsh net-dumpxml network", "Shows network XML configuration"),
        ("virsh pool-list --all", "Lists storage pools"),
        ("virsh pool-info pool", "Shows pool information"),
        ("virsh vol-list pool", "Lists volumes in pool"),
        ("virsh vol-info --pool pool volume", "Shows volume information"),
        ("virt-top", "Virtual machine monitoring"),
        ("virt-viewer domain", "Graphical console for domain"),
        ("virt-manager", "Graphical VM manager"),
        ("qemu-img create -f qcow2 image.qcow2 10G", "Creates QEMU disk image"),
        ("qemu-img convert -f raw -O qcow2 input.img output.qcow2", "Converts disk image format"),
        ("qemu-img info image.qcow2", "Shows disk image information"),
        ("qemu-img resize image.qcow2 +5G", "Resizes disk image"),
        ("qemu-img snapshot -l image.qcow2", "Lists snapshots in disk image"),
        ("qemu-img snapshot -c snapshot image.qcow2", "Creates snapshot"),
        ("qemu-img snapshot -a snapshot image.qcow2", "Applies snapshot"),
        ("qemu-img snapshot -d snapshot image.qcow2", "Deletes snapshot"),
        ("qemu-system-x86_64 -hda disk.img -m 1024", "Runs QEMU VM"),
        ("kvm -hda disk.img -m 1024", "Runs KVM VM"),
        ("docker ps", "Lists running containers"),
        ("docker ps -a", "Lists all containers"),
        ("docker images", "Lists images"),
        ("docker run -it ubuntu bash", "Runs interactive container"),
        ("docker exec -it container bash", "Executes command in running container"),
        ("docker logs container", "Shows container logs"),
        ("docker inspect container", "Shows container details"),
        ("docker stats", "Shows container resource usage"),
        ("docker-compose up", "Starts containers from compose file"),
        ("docker-compose down", "Stops containers from compose file"),
        ("podman ps", "Lists Podman containers"),
        ("podman images", "Lists Podman images"),
        ("lxc list", "Lists LXC containers"),
        ("lxc info container", "Shows container information"),
        ("lxc exec container -- bash", "Executes command in container"),
        ("lxc stop container", "Stops container"),
        ("lxc start container", "Starts container"),
        ("lxc snapshot container", "Creates snapshot"),
        ("lxc restore container snapshot", "Restores snapshot"),
        ("lxc copy container newcontainer", "Copies container"),
        ("lxc delete container", "Deletes container"),
        ("lxd init", "Initializes LXD"),
        ("lxc remote list", "Lists LXD remotes"),
        ("lxc network list", "Lists LXD networks"),
        ("lxc storage list", "Lists LXD storage pools"),
        ("lxc profile list", "Lists LXD profiles"),
        ("lxc config show container", "Shows container configuration"),
        ("lxc config edit container", "Edits container configuration"),
        ("lxc file pull container/path localpath", "Downloads file from container"),
        ("lxc file push localpath container/path", "Uploads file to container"),
        ("lxc image list", "Lists LXD images"),
        ("lxc image import file --alias name", "Imports image"),
        ("lxc image delete name", "Deletes image"),
        ("lxc launch image container", "Creates and starts container from image"),
        ("lxc publish container --alias name", "Creates image from container"),
        ("kubectl get pods", "Lists Kubernetes pods"),
        ("kubectl get nodes", "Lists Kubernetes nodes"),
        ("kubectl get services", "Lists Kubernetes services"),
        ("kubectl get deployments", "Lists Kubernetes deployments"),
        ("kubectl describe pod podname", "Shows pod details"),
        ("kubectl logs podname", "Shows pod logs"),
        ("kubectl exec -it podname -- bash", "Executes command in pod"),
        ("kubectl apply -f file.yaml", "Applies configuration"),
        ("kubectl delete -f file.yaml", "Deletes resources"),
        ("kubectl scale deployment name --replicas=3", "Scales deployment"),
        ("kubectl rollout status deployment/name", "Shows rollout status"),
        ("kubectl rollout undo deployment/name", "Rolls back deployment"),
        ("kubectl config view", "Shows Kubernetes config"),
        ("kubectl cluster-info", "Shows cluster information"),
        ("kubectl top nodes", "Shows node resource usage"),
        ("kubectl top pods", "Shows pod resource usage"),
        ("kubectl get events", "Shows cluster events"),
        ("kubectl get namespaces", "Lists namespaces"),
        ("kubectl create namespace name", "Creates namespace"),
        ("kubectl config set-context --current --namespace=name", "Sets namespace"),
        ("kubectl port-forward podname 8080:80", "Forwards pod port locally"),
        ("kubectl expose deployment name --port=80 --type=LoadBalancer", "Exposes deployment"),
        ("kubectl autoscale deployment name --min=2 --max=5 --cpu-percent=80", "Autoscales deployment"),
        ("kubectl taint nodes node1 key=value:NoSchedule", "Taints node"),
        ("kubectl label nodes node1 key=value", "Labels node"),
        ("kubectl annotate pods podname key=value", "Annotates pod"),
        ("kubectl cordon node1", "Marks node as unschedulable"),
        ("kubectl drain node1", "Drains node for maintenance"),
        ("kubectl uncordon node1", "Marks node as schedulable"),
        ("kubectl get pv", "Lists persistent volumes"),
        ("kubectl get pvc", "Lists persistent volume claims"),
        ("kubectl get storageclass", "Lists storage classes"),
        ("kubectl get secrets", "Lists secrets"),
        ("kubectl get configmaps", "Lists config maps"),
        ("kubectl get ingress", "Lists ingress resources"),
        ("kubectl get daemonsets", "Lists daemon sets"),
        ("kubectl get statefulsets", "Lists stateful sets"),
        ("kubectl get jobs", "Lists jobs"),
        ("kubectl get cronjobs", "Lists cron jobs"),
        ("kubectl get replicasets", "Lists replica sets"),
        ("kubectl get endpoints", "Lists endpoints"),
        ("kubectl get horizontalpodautoscalers", "Lists HPAs"),
        ("kubectl get poddisruptionbudgets", "Lists PDBs"),
        ("kubectl get networkpolicies", "Lists network policies"),
        ("kubectl get rolebindings", "Lists role bindings"),
        ("kubectl get roles", "Lists roles"),
        ("kubectl get clusterroles", "Lists cluster roles"),
        ("kubectl get clusterrolebindings", "Lists cluster role bindings"),
        ("kubectl get serviceaccounts", "Lists service accounts"),
        ("kubectl get priorityclasses", "Lists priority classes"),
        ("kubectl get runtimeclasses", "Lists runtime classes"),
        ("kubectl get volumesnapshots", "Lists volume snapshots"),
        ("kubectl get volumesnapshotclasses", "Lists volume snapshot classes"),
        ("kubectl get volumesnapshotcontents", "Lists volume snapshot contents"),
        ("kubectl get csidrivers", "Lists CSI drivers"),
        ("kubectl get csinodes", "Lists CSI nodes"),
        ("kubectl get storageclasses.storage.k8s.io", "Lists storage classes (full)"),
        ("kubectl get customresourcedefinitions", "Lists CRDs"),
        ("kubectl api-resources", "Lists all API resources"),
        ("kubectl api-versions", "Lists all API versions"),
        ("kubectl explain resource", "Shows resource documentation"),
        ("kubectl version", "Shows client and server version"),
        ("kubectl get --raw /metrics", "Shows raw metrics"),
        ("kubectl get --raw /healthz", "Checks API health"),
        ("kubectl get --raw /readyz", "Checks API readiness"),
        ("kubectl get --raw /apis", "Lists all APIs"),
        ("kubectl get --raw /api/v1", "Lists core v1 API resources"),
        ("kubectl proxy", "Starts proxy to API server"),
        ("kubectl auth can-i create pods", "Checks permissions"),
        ("kubectl auth reconcile -f file.yaml", "Reconciles RBAC"),
        ("kubectl convert -f file.yaml --output-version group/version", "Converts resources"),
        ("kubectl wait --for=condition=Ready pod/podname", "Waits for condition"),
        ("kubectl set image deployment/name container=image", "Updates container image"),
        ("kubectl set env deployment/name KEY=value", "Sets environment variable"),
        ("kubectl set resources deployment/name --limits=cpu=200m,memory=512Mi", "Sets resource limits"),
        ("kubectl set selector service/name key=value", "Sets selector"),
        ("kubectl set serviceaccount deployment/name account", "Sets service account"),
        ("kubectl create secret generic name --from-literal=key=value", "Creates secret"),
        (
        "kubectl create secret docker-registry name --docker-server=server --docker-username=user --docker-password=pass",
        "Creates docker registry secret"),
        ("kubectl create configmap name --from-file=file", "Creates config map"),
        ("kubectl create configmap name --from-literal=key=value", "Creates config map from literal"),
        ("kubectl create job name --image=image -- command", "Creates job"),
        ("kubectl create cronjob name --image=image --schedule=\"*/1 * * * *\" -- command", "Creates cron job"),
        ("kubectl create token servicaccount", "Creates token for service account"),
        ("kubectl create token --duration=24h servicaccount", "Creates token with duration"),
        ("kubectl create token --audience=api servicaccount", "Creates token with audience"),
        ("kubectl create token --bound-object-kind=Pod --bound-object-name=podname servicaccount",
         "Creates bound token"),
        (
        "kubectl create token --bound-object-kind=Pod --bound-object-namespace=ns --bound-object-name=podname servicaccount",
        "Creates namespaced bound token"),
        ("kubectl create token --expiration-seconds=3600 servicaccount", "Creates token with expiration"),
        ("kubectl create token --pod-running-timeout=1m servicaccount", "Creates token with pod timeout"),
        ("kubectl create token --use-group-aliases servicaccount", "Creates token with group aliases"),
        ("kubectl create token --use-pod-identity servicaccount", "Creates token with pod identity"),
        ("kubectl create token --use-service-account-credentials servicaccount", "Creates token with SA credentials"),
        ("kubectl create token --use-service-account-name servicaccount", "Creates token with SA name"),
        ("kubectl create token --use-service-account-uid servicaccount", "Creates token with SA UID"),
        ("kubectl create token --use-service-account-groups servicaccount", "Creates token with SA groups"),
        ("kubectl create token --use-service-account-extra servicaccount", "Creates token with SA extra"),
        ("kubectl create token --use-service-account-annotations servicaccount", "Creates token with SA annotations"),
        ("kubectl create token --use-service-account-labels servicaccount", "Creates token with SA labels"),
        ("kubectl create token --use-service-account-finalizers servicaccount", "Creates token with SA finalizers"),
        ("kubectl create token --use-service-account-owner-references servicaccount",
         "Creates token with SA owner references"),
        ("kubectl create token --use-service-account-managed-fields servicaccount",
         "Creates token with SA managed fields"),
        ("kubectl create token --use-service-account-cluster-info servicaccount", "Creates token with SA cluster info"),
        ("kubectl create token --use-service-account-api-version servicaccount", "Creates token with SA API version"),
        ("kubectl create token --use-service-account-kind servicaccount", "Creates token with SA kind"),
        ("kubectl create token --use-service-account-verbs servicaccount", "Creates token with SA verbs"),
        ("kubectl create token --use-service-account-resources servicaccount", "Creates token with SA resources"),
        ("kubectl create token --use-service-account-short-names servicaccount", "Creates token with SA short names"),
        ("kubectl create token --use-service-account-categories servicaccount", "Creates token with SA categories"),
        ("kubectl create token --use-service-account-columns servicaccount", "Creates token with SA columns"),
        ("kubectl create token --use-service-account-headers servicaccount", "Creates token with SA headers"),
        ("kubectl create token --use-service-account-no-headers servicaccount", "Creates token with SA no headers"),
        ("kubectl create token --use-service-account-output servicaccount", "Creates token with SA output"),
        ("kubectl create token --use-service-account-sort-by servicaccount", "Creates token with SA sort by"),
        ("kubectl create token --use-service-account-template servicaccount", "Creates token with SA template"),
        ("kubectl create token --use-service-account-watch servicaccount", "Creates token with SA watch"),
        ("kubectl create token --use-service-account-watch-only servicaccount", "Creates token with SA watch only"),
        ("kubectl create token --use-service-account-allow-watch-bookmarks servicaccount",
         "Creates token with SA allow watch bookmarks"),
        ("kubectl create token --use-service-account-resource-version servicaccount",
         "Creates token with SA resource version"),
        ("kubectl create token --use-service-account-timeout servicaccount", "Creates token with SA timeout"),
        ("kubectl create token --use-service-account-label-selector servicaccount",
         "Creates token with SA label selector"),
        ("kubectl create token --use-service-account-field-selector servicaccount",
         "Creates token with SA field selector"),
        ("kubectl create token --use-service-account-limit servicaccount", "Creates token with SA limit"),
        ("kubectl create token --use-service-account-continue servicaccount", "Creates token with SA continue"),
        ("kubectl create token --use-service-account-include-uninitialized servicaccount",
         "Creates token with SA include uninitialized"),
        ("kubectl create token --use-service-account-pretty servicaccount", "Creates token with SA pretty"),
        ("kubectl create token --use-service-account-exact servicaccount", "Creates token with SA exact"),
        ("kubectl create token --use-service-account-export servicaccount", "Creates token with SA export"),
        ("kubectl create token --use-service-account-include-extended-apis servicaccount",
         "Creates token with SA include extended APIs"),
        ("kubectl create token --use-service-account-server-print servicaccount", "Creates token with SA server print"),
        ("kubectl create token --use-service-account-show-all servicaccount", "Creates token with SA show all"),
        ("kubectl create token --use-service-account-show-labels servicaccount", "Creates token with SA show labels"),
        ("kubectl create token --use-service-account-silent servicaccount", "Creates token with SA silent"),
        ("kubectl create token --use-service-account-terminated servicaccount", "Creates token with SA terminated"),
        ("kubectl create token --use-service-account-warnings servicaccount", "Creates token with SA warnings"),
        ("kubectl create token --use-service-account-dry-run servicaccount", "Creates token with SA dry run"),
        ("kubectl create token --use-service-account-grace-period servicaccount", "Creates token with SA grace period"),
        ("kubectl create token --use-service-account-orphan servicaccount", "Creates token with SA orphan"),
        ("kubectl create token --use-service-account-cascade servicaccount", "Creates token with SA cascade"),
        ("kubectl create token --use-service-account-deletion-grace-period servicaccount",
         "Creates token with SA deletion grace period"),
        ("kubectl create token --use-service-account-preconditions servicaccount",
         "Creates token with SA preconditions"),
        ("kubectl create token --use-service-account-propagation-policy servicaccount",
         "Creates token with SA propagation policy"),
        ("kubectl create token --use-service-account-selector servicaccount", "Creates token with SA selector"),
        ("kubectl create token --use-service-account-uid servicaccount", "Creates token with SA UID"),
        ("kubectl create token --use-service-account-creation-timestamp servicaccount",
         "Creates token with SA creation timestamp"),
        ("kubectl create token --use-service-account-deletion-timestamp servicaccount",
         "Creates token with SA deletion timestamp"),
        ("kubectl create token --use-service-account-generation servicaccount", "Creates token with SA generation"),
        ("kubectl create token --use-service-account-initializers servicaccount", "Creates token with SA initializers"),
        ("kubectl create token --use-service-account-owner-references servicaccount",
         "Creates token with SA owner references"),
        ("kubectl create token --use-service-account-finalizers servicaccount", "Creates token with SA finalizers"),
        ("kubectl create token --use-service-account-cluster-name servicaccount", "Creates token with SA cluster name"),
        ("kubectl create token --use-service-account-managed-fields servicaccount",
         "Creates token with SA managed fields"),
        ("kubectl create token --use-service-account-api-version servicaccount", "Creates token with SA API version"),
        ("kubectl create token --use-service-account-kind servicaccount", "Creates token with SA kind"),
        ("kubectl create token --use-service-account-verbs servicaccount", "Creates token with SA verbs"),
        ("kubectl create token --use-service-account-resources servicaccount", "Creates token with SA resources"),
        ("kubectl create token --use-service-account-short-names servicaccount", "Creates token with SA short names"),
        ("kubectl create token --use-service-account-categories servicaccount", "Creates token with SA categories"),
        ("kubectl create token --use-service-account-columns servicaccount", "Creates token with SA columns"),
        ("kubectl create token --use-service-account-headers servicaccount", "Creates token with SA headers"),
        ("kubectl create token --use-service-account-no-headers servicaccount", "Creates token with SA no headers"),
        ("kubectl create token --use-service-account-output servicaccount", "Creates token with SA output"),
        ("kubectl create token --use-service-account-sort-by servicaccount", "Creates token with SA sort by"),
        ("kubectl create token --use-service-account-template servicaccount", "Creates token with SA template"),
        ("kubectl create token --use-service-account-watch servicaccount", "Creates token with SA watch"),
        ("kubectl create token --use-service-account-watch-only servicaccount", "Creates token with SA watch only"),
        ("kubectl create token --use-service-account-allow-watch-bookmarks servicaccount",
         "Creates token with SA allow watch bookmarks"),
        ("kubectl create token --use-service-account-resource-version servicaccount",
         "Creates token with SA resource version"),
        ("kubectl create token --use-service-account-timeout servicaccount", "Creates token with SA timeout"),
        ("kubectl create token --use-service-account-label-selector servicaccount",
         "Creates token with SA label selector"),
        ("kubectl create token --use-service-account-field-selector servicaccount",
         "Creates token with SA field selector"),
        ("kubectl create token --use-service-account-limit servicaccount", "Creates token with SA limit"),
        ("kubectl create token --use-service-account-continue servicaccount", "Creates token with SA continue"),
        ("kubectl create token --use-service-account-include-uninitialized servicaccount",
         "Creates token with SA include uninitialized"),
        ("kubectl create token --use-service-account-pretty servicaccount", "Creates token with SA pretty"),
        ("kubectl create token --use-service-account-exact servicaccount", "Creates token with SA exact"),
        ("kubectl create token --use-service-account-export servicaccount", "Creates token with SA export"),
        ("kubectl create token --use-service-account-include-extended-apis servicaccount",
         "Creates token with SA include extended APIs"),
        ("kubectl create token --use-service-account-server-print servicaccount", "Creates token with SA server print"),
        ("kubectl create token --use-service-account-show-all servicaccount", "Creates token with SA show all"),
        ("kubectl create token --use-service-account-show-labels servicaccount", "Creates token with SA show labels"),
        ("kubectl create token --use-service-account-silent servicaccount", "Creates token with SA silent"),
        ("kubectl create token --use-service-account-terminated servicaccount", "Creates token with SA terminated"),
        ("kubectl create token --use-service-account-warnings servicaccount", "Creates token with SA warnings"),
        ("kubectl create token --use-service-account-dry-run servicaccount", "Creates token with SA dry run"),
        ("kubectl create token --use-service-account-grace-period servicaccount", "Creates token with SA grace period"),
        ("kubectl create token --use-service-account-orphan servicaccount", "Creates token with SA orphan"),
        ("kubectl create token --use-service-account-cascade servicaccount", "Creates token with SA cascade"),
        ("kubectl create token --use-service-account-deletion-grace-period servicaccount",
         "Creates token with SA deletion grace period"),
        ("kubectl create token --use-service-account-preconditions servicaccount",
         "Creates token with SA preconditions"),
        ("kubectl create token --use-service-account-propagation-policy servicaccount",
         "Creates token with SA propagation policy"),
        ("kubectl create token --use-service-account-selector servicaccount", "Creates token with SA selector"),
        ("kubectl create token --use-service-account-uid servicaccount", "Creates token with SA UID"),
        ("kubectl create token --use-service-account-creation-timestamp servicaccount",
         "Creates token with SA creation timestamp"),
        ("kubectl create token --use-service-account-deletion-timestamp servicaccount",
         "Creates token with SA deletion timestamp"),
        ("kubectl create token --use-service-account-generation servicaccount", "Creates token with SA generation"),
        ("kubectl create token --use-service-account-initializers servicaccount", "Creates token with SA initializers"),
        ("kubectl create token --use-service-account-owner-references servicaccount",
         "Creates token with SA owner references"),
        ("kubectl create token --use-service-account-finalizers servicaccount", "Creates token with SA finalizers"),
        ("kubectl create token --use-service-account-cluster-name servicaccount", "Creates token with SA cluster name"),
        ("kubectl create token --use-service-account-managed-fields servicaccount",
         "Creates token with SA managed fields"),
        ("kubectl create token --use-service-account-api-version servicaccount", "Creates token with SA API version"),
        ("kubectl create token --use-service-account-kind servicaccount", "Creates token with SA kind"),
        ("kubectl create token --use-service-account-verbs servicaccount", "Creates token with SA verbs"),
        ("kubectl create token --use-service-account-resources servicaccount", "Creates token with SA resources"),
        ("kubectl create token --use-service-account-short-names servicaccount", "Creates token with SA short names"),
        ("kubectl create token --use-service-account-categories servicaccount", "Creates token with SA categories"),
        ("kubectl create token --use-service-account-columns servicaccount", "Creates token with SA columns"),
        ("kubectl create token --use-service-account-headers servicaccount", "Creates token with SA headers"),
        ("kubectl create token --use-service-account-no-headers servicaccount", "Creates token with SA no headers"),
        ("kubectl create token --use-service-account-output servicaccount", "Creates token with SA output"),
        ("kubectl create token --use-service-account-sort-by servicaccount", "Creates token with SA sort by"),
        ("kubectl create token --use-service-account-template servicaccount", "Creates token with SA template"),
        ("kubectl create token --use-service-account-watch servicaccount", "Creates token with SA watch"),
        ("kubectl create token --use-service-account-watch-only servicaccount", "Creates token with SA watch only"),
        ("kubectl create token --use-service-account-allow-watch-bookmarks servicaccount",
         "Creates token with SA allow watch bookmarks"),
        ("kubectl create token --use-service-account-resource-version servicaccount",
         "Creates token with SA resource version"),
        ("kubectl create token --use-service-account-timeout servicaccount", "Creates token with SA timeout"),
        ("kubectl create token --use-service-account-label-selector servicaccount",
         "Creates token with SA label selector"),
        ("kubectl create token --use-service-account-field-selector servicaccount",
         "Creates token with SA field selector"),
        ("kubectl create token --use-service-account-limit servicaccount", "Creates token with SA limit"),
        ("kubectl create token --use-service-account-continue servicaccount", "Creates token with SA continue"),
        ("kubectl create token --use-service-account-include-uninitialized servicaccount",
         "Creates token with SA include uninitialized"),
        ("kubectl create token --use-service-account-pretty servicaccount", "Creates token with SA pretty"),
        ("kubectl create token --use-service-account-exact servicaccount", "Creates token with SA exact"),
        ("kubectl create token --use-service-account-export servicaccount", "Creates token with SA export"),
        ("kubectl create token --use-service-account-include-extended-apis servicaccount",
         "Creates token with SA include extended APIs"),
        ("kubectl create token --use-service-account-server-print servicaccount", "Creates token with SA server print"),
        ("kubectl create token --use-service-account-show-all servicaccount", "Creates token with SA show all"),
        ("kubectl create token --use-service-account-show-labels servicaccount", "Creates token with SA show labels"),
        ("kubectl create token --use-service-account-silent servicaccount", "Creates token with SA silent"),
        ("kubectl create token --use-service-account-terminated servicaccount", "Creates token with SA terminated"),
        ("kubectl create token --use-service-account-warnings servicaccount", "Creates token with SA warnings"),
        ("kubectl create token --use-service-account-dry-run servicaccount", "Creates token with SA dry run"),
        ("kubectl create token --use-service-account-grace-period servicaccount", "Creates token with SA grace period")

    ]

    mac_commands = [
        # mac commands
        ("system_profiler SPHardwareDataType", "Displays detailed hardware information"),
        ("sw_vers", "Shows macOS version"),
        ("uname -a", "Displays kernel and system info"),
        ("hostinfo", "Shows host information"),
        ("uptime", "Shows system uptime"),
        ("whoami", "Current logged-in user"),
        ("id", "User ID and group IDs"),
        ("groups", "Groups of current user"),
        ("dscl . list /Users", "Lists all users on system"),
        ("dscl . list /Groups", "Lists all groups on system"),

        # CPU & Memory
        ("sysctl -n machdep.cpu.brand_string", "CPU model name"),
        ("sysctl -a | grep cpu", "Detailed CPU info"),
        ("vm_stat", "Virtual memory statistics"),
        ("top -l 1 | head -n 10", "Top CPU-consuming processes"),
        ("ps aux", "List all running processes"),
        ("htop", "Interactive process viewer (if installed)"),
        ("system_profiler SPMemoryDataType", "RAM details"),
        ("sysctl hw.memsize", "Total memory size in bytes"),

        # Disk & Storage
        ("diskutil list", "List all disks and partitions"),
        ("df -h", "Disk usage summary"),
        ("du -sh *", "Size of files/folders in current directory"),
        ("ls -l /Volumes", "Mounted volumes"),
        ("system_profiler SPStorageDataType", "Detailed storage info"),
        ("diskutil info /", "Info about main volume"),

        # Network
        ("ifconfig", "Network interfaces and IPs"),
        ("ipconfig getifaddr en0", "IP of primary interface"),
        ("netstat -an", "All network connections"),
        ("netstat -rn", "Routing table"),
        ("ping -c 4 8.8.8.8", "Ping Google DNS"),
        ("traceroute 8.8.8.8", "Trace route to Google DNS"),
        ("nslookup google.com", "DNS lookup"),
        ("dig google.com", "Detailed DNS query"),
        ("arp -a", "ARP table"),
        ("route get default", "Default gateway"),
        ("scutil --dns", "DNS resolver info"),

        # Users & Permissions
        ("who", "Logged-in users"),
        ("last", "Last logins"),
        ("id username", "Specific user info"),
        ("ls -la /Users", "List all user home directories"),
        ("sudo dscl . read /Users/username", "Read user info"),
        ("groups username", "Groups for a specific user"),
        ("sudo dscacheutil -q group", "All groups on system"),

        # Software & Packages
        ("brew list", "Installed Homebrew packages"),
        ("brew info package_name", "Details about a package"),
        ("pkgutil --pkgs", "List installed packages"),
        ("system_profiler SPApplicationsDataType", "List installed apps"),
        ("defaults read /Library/Preferences/com.apple.loginwindow", "Login window preferences"),

        # Startup & Services
        ("launchctl list", "All loaded launch agents/daemons"),
        ("sudo launchctl list", "Loaded system services"),
        ("systemsetup -getstartupdisk", "Current startup disk"),
        ("sudo systemsetup -gettimezone", "System timezone"),

        # Security
        ("csrutil status", "System Integrity Protection status"),
        ("spctl --status", "Gatekeeper status"),
        ("sudo fdesetup status", "FileVault encryption status"),
        ("sudo defaults read /Library/Preferences/com.apple.alf globalstate", "Firewall status"),

        # Files & Directories
        ("ls -la", "List files with details"),
        ("find / -type f -name '*.conf'", "Find configuration files"),
        ("mdfind 'kMDItemFSName == *.txt'", "Spotlight search for .txt files"),
        ("ls -lh /Applications", "List applications with sizes"),
        ("du -sh /Users/*", "Disk usage per user"),

        # Clipboard & Logs
        ("pbpaste", "Show clipboard content"),
        ("pbcopy", "Copy content to clipboard"),
        ("log show --predicate 'eventMessage contains \"error\"' --last 1d", "System logs with errors"),
        ("log show --last 1h", "Recent logs"),

        # Hardware Info Advanced
        ("system_profiler SPDisplaysDataType", "Graphics/display info"),
        ("system_profiler SPAudioDataType", "Audio devices"),
        ("system_profiler SPBluetoothDataType", "Bluetooth devices"),
        ("system_profiler SPUSBDataType", "USB devices"),
        ("system_profiler SPCardReaderDataType", "Card readers"),
        ("system_profiler SPNetworkDataType", "Network adapters"),
        ("system_profiler SPPrintersDataType", "Printer info"),

        # Environment & Variables
        ("printenv", "Print all environment variables"),
        ("echo $PATH", "Show PATH variable"),
        ("echo $HOME", "Home directory"),
        ("echo $SHELL", "Default shell"),
        ("env", "Environment variables list"),

        # Processes
        ("ps -ef", "Detailed list of all processes"),
        ("pgrep process_name", "Get PID of process by name"),
        ("kill PID", "Kill a process by PID"),
        ("killall process_name", "Kill process by name"),

        # Cron & Jobs
        ("crontab -l", "List user cron jobs"),
        ("sudo crontab -l", "List root cron jobs"),
        ("launchctl list", "List user launch agents"),

        # System Stats
        ("uptime", "System uptime"),
        ("vm_stat", "Virtual memory statistics"),
        ("iostat", "CPU and IO statistics"),
        ("nettop -P -L 1", "Real-time network activity"),

        # Misc
        ("whoami", "Current user"),
        ("uptime", "System uptime"),
        ("date", "Current date and time"),
        ("cal", "Show calendar"),
        ("history", "Command history"),
        ("echo $SHELL", "Default shell"),
        ("w", "Logged in users and activity"),
        ("finger username", "User info if available"),

        # Package Management
        ("brew update", "Update Homebrew"),
        ("brew upgrade", "Upgrade installed packages"),
        ("brew doctor", "Check Homebrew health"),

        # Network Advanced
        ("lsof -i", "List open internet connections"),
        ("nettop -m tcp -x", "Live TCP connections"),
        ("tcpdump -i en0 -c 10", "Capture network packets"),
        ("nmap localhost", "Scan localhost ports"),

        # Misc System Checks
        ("system_profiler SPSoftwareDataType", "OS and system software info"),
        ("defaults read NSGlobalDomain AppleInterfaceStyle", "Check dark/light mode"),
        ("pmset -g batt", "Battery status"),
        ("system_profiler SPFirewallDataType", "Firewall info"),
        ("sysctl hw.model", "Hardware model"),
        ("sysctl hw.ncpu", "Number of CPU cores"),
        ("sysctl hw.cpufrequency", "CPU frequency"),

        # User History & Logs
        ("last", "Login history"),
        ("last reboot", "System reboot history"),
        ("log show --predicate 'eventMessage contains \"login\"' --last 1d", "Login events last day"),

        # Disk Encryption & Security
        ("diskutil cs list", "CoreStorage volumes (FileVault)"),
        ("fdesetup list", "List FileVault-enabled users"),

        # Network Config
        ("networksetup -listallhardwareports", "All network interfaces"),
        ("networksetup -getinfo Wi-Fi", "Wi-Fi interface info"),
        ("networksetup -getairportnetwork en0", "Connected Wi-Fi SSID"),

        # Connectivity
        ("ping -c 4 1.1.1.1", "Ping Cloudflare DNS"),
        ("curl ifconfig.me", "Get public IP"),
        ("dig +short myip.opendns.com @resolver1.opendns.com", "Another public IP lookup"),

        # Applications
        ("open -a Safari", "Open Safari browser"),
        ("open -a Terminal", "Open Terminal"),
        ("open -a Finder", "Open Finder"),

        # File Search
        ("find /Users -name '*.pdf'", "Search for PDF files in users"),
        ("find /Users -name '*.docx'", "Search for Word documents"),
        ("find /Users -name '*.xlsx'", "Search for Excel files"),

        # Time & Scheduler
        ("date", "Show current date/time"),
        ("cal", "Show calendar"),
        ("pmset -g sched", "Show scheduled power events"),

        # Audio & Video
        ("system_profiler SPAudioDataType", "Audio device info"),
        ("system_profiler SPDisplaysDataType", "Video/display info"),

        # Misc Utilities
        ("uptime", "System uptime"),
        ("who", "Logged-in users"),
        ("w", "Active users and processes"),
        ("last", "Login history"),
        ("history", "Command history"),
        ("echo $PATH", "Show PATH environment"),
        ("echo $HOME", "Home directory"),
        ("echo $SHELL", "Default shell"),
    ]

    if choice == "1":
        cmds_to_show = windows_cmds
        platform_name = "Windows"
    elif choice == "2":
        cmds_to_show = linux_cmds
        platform_name = "Linux/Mac"
    elif choice == "3":
        cmds_to_show = mac_commands
        platform_name = "Mac"
    else:
        print("[!] Invalid choice, defaulting to current system commands")
        current_system = platform.system()
        cmds_to_show = windows_cmds if current_system == "Windows" else linux_cmds
        platform_name = current_system

    print(f"\n--- Useful commands for {platform_name} ---\n")
    for cmd, desc in cmds_to_show:
        print(f"{cmd}  --> {desc}")


if __name__ == "__main__":
    full_useful_commands()